language: java

jdk:
  - oraclejdk8

install:
  - pip install --user codecov
after_success:
  - codecov

test:
    post:
        - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
        - bash <(curl -s https://codecov.io/bash)
